language: go

install:
    - go get github.com/stretchr/testify/assert
    - go get golang.org/x/tools/cmd/cover
    - go get github.com/mattn/goveralls
  
script:
    - go test -v -cover -covermode=count -coverprofile=coverage.out .
    - $(go env GOPATH | awk 'BEGIN{FS=":"} {print $1}')/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken=$COVERALLS_TOKEN